### PR TITLE
fix: change incorrect spelling of Multiplication in math helper

### PR DESCRIPTION
**Pull request by hharchani**
## What does this PR do?

It fixes the spelling of Multiplication in math helper which was incorrectly there as Multiplicattion

### CODE REVIEW

**Comment by abuaboud** [comment]
@allcontributors please add @hharchani for plugin

**Comment by abuaboud** [comment]
Hi @hharchani 

Can you please bump the version in package.json in the same directory

**Comment by hharchani** [comment]
Hi @abuaboud 

Bumped the version to 0.26.2

**Comment by abuaboud** [comment]
Sorry for @hharchani confusion, can you revert this package.json.

We need to bump the one that related to this piece here -> https://github.com/activepieces/activepieces/blob/677d4abe916d9582bd348e6b226208ff957cfd5f/packages/pieces/community/math-helper/package.json

Also it would be great If you can sign the CLA, so i can merge it :D

**Pull request merged**
