### PR TITLE
feat(gameball): add gameball piece and send-event action

### PR DESCRIPTION
**Pull request by Raamyy**
## What does this PR do?

gameball-logo

This PR adds the integration with [Gameball](https://www.gameball.co) as a piece and add basic action of sending an event to gameball systems

### CODE REVIEW

**Comment by abuaboud** [comment]
@allcontributors please add @Raamyy for plugin

**Comment by abuaboud** [comment]
I am big fan of Gameball, I remember having a great conversation with the founders in step event in 2022 ! :D

**Comment by Raamyy** [comment]
Thanks @abuaboud

I am glad that gameball became a small "piece" of active pieces now. 😄

**Comment by Raamyy** [comment]
@abuaboud  The uploaded logo image is an outdated one, Gameball just had a recent rebranding. Let me know how can I update the cdn image with the updated logo. 🤝

**Pull request merged**
