### PR TITLE
feat(openai): New Embedding Action

### PR DESCRIPTION
**Pull request by Armangiau**
## What does this PR do?

This is a new action for the OpenAI piece. It allows you to create an index of a text for similarity search or other purposes. To do this, the action transforms the text into an embedding, which is a numerical representation of the text. However, if your text is too large, it will be difficult to query it efficiently. Therefore, the piece splits the text into different chunks and creates embeddings for each chunk.

### CODE REVIEW

**Comment by abuaboud** [comment]
@Armangiau, I find this really interesting, and I'll merge it soon.

Are you available on Discord? My username is abuaboud.

I would love to learn more about embedding and how we can create templates for it's use cases. We're also integrating with more LLM soon too.

**Comment by Armangiau** [comment]
This pull request is not up to date, delete reject it

**Comment by Armangiau** [comment]
Go to [this pull request](https://github.com/activepieces/activepieces/pull/2416)

**Comment by abuaboud** [comment]
https://github.com/activepieces/activepieces/pull/2416

**Pull request closed without merging**
