### PR TITLE
feat(chargekeep): create invoice, create contact , create subscription  actions and 3 triggers

### PR DESCRIPTION
**Pull request by Trayshmhirk**
## What does this PR do?

This pull request introduces a new integration piece for ChargeKeep. It adds support for ChargeKeep’s Beta API, allowing users to interact with ChargeKeep through ActivePieces.

### Changes Made
- Added a ChargeKeep piece: This includes actions and triggers to integrate with ChargeKeep’s API.
- Implemented subscription and unsubscription features: Users can now subscribe to ChargeKeep events and manage webhooks.
- Included error handling and validation: Ensures robust interaction with the ChargeKeep API.

### Additional Notes
- Please review the integration to ensure it adheres to the coding standards and practices of the main repository.
- Feedback on any additional features or improvements is welcome.

### CODE REVIEW

**Comment by Trayshmhirk** [comment]
Hi @maintainers,

I hope this message finds you well. I wanted to follow up on this pull request. If there's anything I can do to help with the review process or if any changes are needed, please let me know. I'm available to make any necessary adjustments.

Thank you for your time and consideration.

Best regards,
Frank Micheal

**Comment by kishanprmr** [comment]
Hi @Trayshmhirk ,

I’m reviewing this PR and referring to the [API documentation](https://www.chargekeep.com/api/). However, I couldn’t find the endpoint for the ‘Add or Update Contact’ action. Could you please provide an updated link to the API documentation or any additional information?

**Comment by Trayshmhirk** [comment]
Hello @kishanprmr,

The link to the api documentation has to be https://beta.chargekeep.com/
You can get a direct access to the API documentation through this link https://beta.chargekeep.com/api/index.html, although you may have to log in to test the endpoints.

Also, the endpoint for the Add or Update Contact action that was used "/Import/ImportContact" is correct and is tested for its purpose.

If there is anything else that needs to be reviewed, i'd be glad to cooperate with any adjustments to be made.

**Comment by kishanprmr** [comment]
@allcontributors please add @Trayshmhirk  for plugin

**Review by kishanprmr — APPROVED** [review]

**Comment by Trayshmhirk** [comment]
@kishanprmr  Thank you for the review and approval! Will the merge of this PR be handled? I am yet to see the merge to the main branch.

**Comment by abuaboud** [comment]
Thank you so much, I uploaded the logo and merged. :D

**Pull request merged**
