### PR TITLE
feat: add qrcode piece

### PR DESCRIPTION
**Pull request by MrMYHuang**
The new qrcode piece supports text to QR code conversion.

The output format supports:
1. memory://: it is supported by [readApFile](https://github.com/activepieces/activepieces/blob/9c4581bcf5875ff7147dd33b86d6080907c33c7a/packages/engine/src/lib/services/files.service.ts#L33)
2. Base64 data URI: it starts with 'data:image/png;base64,`
3. Buffer (PNG): PNG data in NodeJS Buffer

### CODE REVIEW

**Comment by kishanprmr** [comment]
@MrMYHuang, I have removed the output format dropdown and made the result file URL part of the response. This URL can be converted to base64 using the Image Helper piece. What do you think?

**Comment by MrMYHuang** [comment]
> @MrMYHuang, I have removed the output format dropdown and made the result file URL part of the response. This URL can be converted to base64 using the Image Helper piece. What do you think?

Thank you. I tested the combination. It works.

**Comment by abuaboud** [comment]
Hi @MrMYHuang 

Can you delete the uuid package, delete the commented code, add core category similar to other core pieces. 

Let's merge it after :D

**Comment by MrMYHuang** [comment]
> Hi @MrMYHuang
> 
> Can you delete the uuid package, delete the commented code, add core category similar to other core pieces.
> 
> Let's merge it after :D

Please review the commit [9b74379](https://github.com/activepieces/activepieces/pull/5525/commits/9b743792303d545f57ebc0341a9550225664d481). Thank you.

**Pull request merged**
