### PR TITLE
feat: jotform piece

### LINKED ISSUE #883: Jotform - new Submission

### PR DESCRIPTION
**Pull request by MoShizzle**
Creates a Jotform piece with trigger for new submissions

Fixed #883

### CODE REVIEW

**Comment by MoShizzle** [comment]
#883

**Comment by abuaboud** [comment]
I keep getting the following error when testing

```
[API] [15:41:58 UTC] ERROR: [HttpClient#sendRequest] error, responseStatus: 400
[API] [15:41:58 UTC] ERROR: [HttpClient#sendRequest] error, responseBody: {
[API] [15:41:58 UTC] ERROR:   responseCode: 400,
[API] [15:41:58 UTC] ERROR:   message: 'WebHook URL is wrong. (Example : http://www.myhost.com/post.php)',
[API] [15:41:58 UTC] ERROR:   content: '',
[API] [15:41:58 UTC] ERROR:   duration: '19.80ms',
[API] [15:41:58 UTC] ERROR:   info: 'https://api.jotform.com/docs#form-id-webhooks'
[API] [15:41:58 UTC] ERROR: }
[API] [15:41:58 UTC] ERROR: HttpError: {"response":{"status":400,"body":{"responseCode":400,"message":"WebHook URL is wrong. (Example : http://www.myhost.com/post.php)","content":"","duration":"19.80ms","info":"https://api.jotform.com/docs#form-id-webhooks"}},"request":{"body":"webhookURL=https://fc2a-2a02-810d-980-53b4-caf8-1a3-deec-2f52.eu.ngrok.io/v1/webhooks/bNhjfx99zGyxzsinEFL1o"}}
````

Did you face similar issue?

**Comment by abuaboud** [comment]
I merged with main and also added support for europe

**Comment by MoShizzle** [comment]
> I keep getting the following error when testing
> 
> ```
> [API] [15:41:58 UTC] ERROR: [HttpClient#sendRequest] error, responseStatus: 400
> [API] [15:41:58 UTC] ERROR: [HttpClient#sendRequest] error, responseBody: {
> [API] [15:41:58 UTC] ERROR:   responseCode: 400,
> [API] [15:41:58 UTC] ERROR:   message: 'WebHook URL is wrong. (Example : http://www.myhost.com/post.php)',
> [API] [15:41:58 UTC] ERROR:   content: '',
> [API] [15:41:58 UTC] ERROR:   duration: '19.80ms',
> [API] [15:41:58 UTC] ERROR:   info: 'https://api.jotform.com/docs#form-id-webhooks'
> [API] [15:41:58 UTC] ERROR: }
> [API] [15:41:58 UTC] ERROR: HttpError: {"response":{"status":400,"body":{"responseCode":400,"message":"WebHook URL is wrong. (Example : http://www.myhost.com/post.php)","content":"","duration":"19.80ms","info":"https://api.jotform.com/docs#form-id-webhooks"}},"request":{"body":"webhookURL=https://fc2a-2a02-810d-980-53b4-caf8-1a3-deec-2f52.eu.ngrok.io/v1/webhooks/bNhjfx99zGyxzsinEFL1o"}}
> ```
> 
> Did you face similar issue?

Jotform doesn't like ngrok links (Facebook too), try using https://serveo.net/ for exposing localhost

**Comment by abuaboud** [comment]
I think its full, is it working for you I can double check?

**Review by abuaboud — DISMISSED** [review]

**Pull request merged**
