### PR TITLE
feat(piece-framework): support array of objects

### PR DESCRIPTION
**Pull request by Anomaly314**
feat: add nested property access support in array for nested forms

Testing:
Manual testing confirms that refreshers mechanisms, dynamic property assignment, and validations are fully functional.

Sample Code:

```
    simpleArray: Property.Array({
      displayName: 'Simple Array',
      required: false,
    }),
    array: Property.Array({
      displayName: 'Nested Array',
      required: false,
      properties: {
        text: Property.ShortText({
          displayName: 'short',
          required: true,
        }),
        staticSelect: Property.StaticDropdown({
          displayName: 'Key-2',
          required: true,
          options: {
            options: [
              { label: 'val1', value: 1 },
              { label: 'val2', value: 2 },
            ],
          },
        }),
        checkbox: Property.Checkbox({
          displayName: 'Agree to Terms',
          description: 'Check this box to agree to the terms',
          required: true,
          defaultValue: false,
        }),
        number: Property.Number({
          displayName: 'Quantity',
          description: 'Enter a number',
          required: true,
        }),
        mutlistatic: Property.StaticMultiSelectDropdown({
          displayName: 'Colors',
          description: 'Select one or more colors',
          required: true,
          options: {
            options: [
              {
                label: 'Red',
                value: 'red',
              },
              {
                label: 'Green',
                value: 'green',
              },
              {
                label: 'Blue',
                value: 'blue',
              },
            ],
          },
        }),
        dropdown: Property.Dropdown<string>({
          displayName: 'Options',
          description: 'Select an option',
          required: true,
          refreshers: [],
          options: async () => {
            return {
              options: [
                {
                  label: 'Option One',
                  value: '1',
                },
                {
                  label: 'Option Two',
                  value: '2',
                },
              ],
            };
          },
        }),
        multi: Property.MultiSelectDropdown<string>({
          displayName: 'Options',
          description: 'Select one or more options',
          required: true,
          refreshers: [],
          options: async () => {
            const apiEndpoint = 'https://jsonplaceholder.typicode.com/todos';
            const response = await fetch(apiEndpoint);
            const data: { id: number; title: string }[] = await response.json();
            return {
              options: data.map((item) => {
                return { value: item.id?.toString(), label: item.title };
              }),
            };
          },
        }),
        dynamic: Property.DynamicProperties({
          description: 'Dynamic Form',
          displayName: 'Dynamic Form',
          required: true,
          refreshers: [],
          props: async (propsValue) => {
            const apiEndpoint = 'https://jsonplaceholder.typicode.com/todos';
            const response = await fetch(apiEndpoint);
            const data: { id: number; title: string }[] = await response.json();

            const properties = {
              prop1: Property.StaticDropdown({
                displayName: 'Property 1',
                description: 'Enter property 1',
                required: true,
                options: {
                  options: data.map((item) => {
                    return { value: item.id?.toString(), label: item.title };
                  }),
                },
              }),
            };

            return properties;
          },
        }),
      },
    }),

```

Screenshot from 2023-10-16 18-45-02
Screenshot from 2023-10-16 18-44-49

### CODE REVIEW

**Comment by abuaboud** [comment]
Hi @awais000 give me some more time, I am going to get back to that soon!

Sorry

**Comment by fardeenpanjwani-codeglo** [comment]
@awais000, very useful feature! Thanks! Just out of curiosity, is there a way to make one property's config depend on value from another property ( both property being in the same array )?

**Comment by abuaboud** [comment]
Thank you, @Anomaly314, for this great contribution.

As we discussed, let's temporarily remove the dynamic dropdown and dynamic properties, and then merge that.

I have merged with the main branch and pushed the changes we discussed.

@AbdulTheActivePiecer, could you please take a look at the user interface and make the necessary changes?

I believe we should take look at the design of groups at https://github.com/activepieces/activepieces/pull/3206 and ensure that we have a design for grouping (card), that we will be using in both these feature.

**Comment by AbdulTheActivePiecer** [comment]
Hi there guys, I adjusted some stuff in the UI code to make it more coherent with our design, thanks a lot @Anomaly314.
One of the thing I would like to recommend is moving shared code/logic into a separate file, instead of passing it as an input parameter to a child component, that's just a recipe of disaster because of side-effects that could happen, believe me I tried it before 😂
Another thing is to not include the "valueChanges" listener in writeValue as that's not recommended in Angular, because writeValue can be called programatically and not only on initialization of the form control.
Other than that all was great

**Pull request merged**
