### PR TITLE
feat(google-gemini): migrate to official SDK and prioritize gemini-1.5-flash support

### PR DESCRIPTION
**Pull request by mordonez**
This PR migrates Gemini actions to use the official SDK with a focus on the high-performance `gemini-1.5-flash` model.

### Motivation

- Gemini 1.0 Pro Vision is already deprecated (July 12, 2024)
- Vision API returning 404 errors
```json
{
  "response": {
    "status": 404,
    "body": {
      "error": {
        "code": 404,
        "message": "Gemini 1.0 Pro Vision has been deprecated on July 12, 2024. Consider switching to different model, for example gemini-1.5-flash.2025. ",
        "status": "NOT_FOUND"
      }
    }
  }
}
```

### Dependencies Added
```json
{
  "dependencies": {
    "@google/generative-ai": "^0.21.0"
  }
}
```
## Key Changes
- Migrate REST API calls to official [@google/generative-ai](https://github.com/google-gemini/generative-ai-js) SDK
- Add support for new Gemini 1.5 models:
  - gemini-1.5-flash (default, optimized for speed)
  - gemini-1.5-flash-8b (lightweight version)
  - gemini-1.5-pro (enhanced capabilities)
- Refactor actions:
  - generate-content
  - chat-gemini
  - generate-content-from-image
- Add common utilities in commons.ts

## SDK Documentation
[Official Documentation](https://ai.google.dev/gemini-api/docs/quickstart?lang=node)

### CODE REVIEW

**Comment by abuaboud** [comment]
Thank you for the contribution :D 

Can you please bump the package.json the patch version in the piece.

**Comment by abuaboud** [comment]
I sent you a connection request on LinkedIn with the gift link provided.  

We’d love to send an Activepieces SWAG gift to every contributor. It’s a small gesture, but I hope you like it.

**Comment by abuaboud** [comment]
@allcontributors please add @mordonez for piece

**Comment by abuaboud** [comment]
@allcontributors please add @mordonez for integration

**Comment by abuaboud** [comment]
@allcontributors please add @mordonez for plugin

**Comment by mordonez** [comment]
Hi @abuaboud I recently merged the latest changes from main into this branch to keep it up to date. However, I’ve noticed that this has added all the recent main commits into this pull request, which might make the review process harder.

To address this, I would like your feedback

a - Rollback the merge with a force reset, this would make the PR cleaner but would involve a force push, which changes the branch history
b- Keep the merge as is

Please let me know which approach you prefer. I’m happy to adjust based on your preferences.
Miguel

**Comment by abuaboud** [comment]
I believe you can cherry pick your commits on clean branch, that should work, what do you think?

**Comment by abuaboud** [comment]
Closing in favor of https://github.com/activepieces/activepieces/pull/6256

**Pull request closed without merging**
