### PR TITLE
Configure AllContributors Bot

### PR DESCRIPTION
**Pull request by mabumusa1**
Right now this repo uses Allcontributors, but it the content of the bot HTML is hardcoded, this needs to be done via a src file, this PR make the required changes

### CODE REVIEW

**Comment by abuaboud** [comment]
@all-contributors
please add @khaledmashaly  for maintaining. 
please add @abuaboud  for maintaining. 
please add @AbdulTheActivePiecer  for maintaining. 
please add @mabumusa1  for repository setup.

**Comment by abuaboud** [comment]
@all-contributors please add @khaledmashaly  for maintaining. please add @abuaboud  for maintaining.  please add @AbdulTheActivePiecer  for maintaining. please add @mabumusa1  for repository setup.

**Comment by abuaboud** [comment]
please add @mabumusa1 for repository setup.

**Comment by abuaboud** [comment]
@all-contributors please add @mabumusa1 for repository setup.

**Comment by mabumusa1** [comment]
@abuaboud you need the file you deleted , it is the array that all contributors change

**Comment by abuaboud** [comment]
> @abuaboud you need the file you deleted , it is the array that all contributors change

Ouch thank you!

**Comment by abuaboud** [comment]
@all-contributors please add @khaledmashaly  for maintaining.

**Comment by abuaboud** [comment]
@all-contributors please add @mabumusa1  for maintaining.

**Comment by abuaboud** [comment]
@all-contributors please add @abuaboud for maintaining.

**Comment by mabumusa1** [comment]
@abuaboud please edit readme.md it is not well formatted. But I think the bot worked as expected

**Comment by abuaboud** [comment]
@all-contributors please add @AbdulTheActivePiecer for maintaining.

**Comment by abuaboud** [comment]
I will close the PR and add the two remaining contributors later, once the bot is up again.

**Comment by john-jova** [comment]
Phase 3 complete — merged to main. All VM tests pass.

**Pull request merged**
