### PR TITLE
feat(salesforce): add conditions to trigger / bulk upsert action

### PR DESCRIPTION
**Pull request by landonmoir**
## What does this PR do?

Add a bulk upsert action to the Salesforce piece to allow for inserting more than the current 200 record limit.

As such, I had to add to the HttpClient the option to accept 'text/csv' content for a post request, since it defaults to 'application/json' even if you specify a custom header in the send request function call.

Additionally, I've added the ability to add SOQL query conditions to the new-record and new-or-updated-record triggers. This is useful for when a Salesforce org has many bulk loads that can possibly trigger thousands of flow runs in AP even if they end quickly due to a branch block.

ANNOUNCEMENT=true

### CODE REVIEW

**Comment by landonmoir** [comment]
Rework of #2255

**Comment by abuaboud** [comment]
Hi @landonmoir 

Thank you for the rework, I will review this soon thank you for the patience.

**Review by abuaboud — DISMISSED** [review]

**Comment by landonmoir** [comment]
@abuaboud noticed I forgot to increment the version in packages/pieces/common, the workflows should pass now

**Comment by landonmoir** [comment]
@abuaboud Let me know if theres anything you need from me to help get this merged :)

**Comment by landonmoir** [comment]
@abuaboud is there a way to run the validate-publishable-packages action on commit? the package versions in this PR keep getting out of sync with main, causing this endless cycle of workflow failures every few days. It would be great to get this merged soon as my team has a few projects that depend on this feature :)

**Review by abuaboud — APPROVED** [review]

**Review by abuaboud — APPROVED** [review]

**Pull request merged**
