### PR TITLE
feat(whatsapp): Send Template Message Action

### PR DESCRIPTION
**Pull request by coderbob2**
### Whatsapp send from template action is added to whatsapp piece

I have added an action on whatsapp piece and added send from template feature to enable sending cloud api messages from templates, the action will fetch existing templates and also adds dynamic props depending on the selected template. it also provides example values if available from the template.

ANNOUNCEMENT=true

### CODE REVIEW

**Review by coderbob2 — COMMENTED** [review]
code refactored for const values

**Comment by abuaboud** [comment]
Hi @coderbob2 

@kishanprmr will take look soon :D

**Comment by coderbob2** [comment]
> Hi @coderbob2
> 
> @kishanprmr will take look soon :D

@kishanprmr any update ?

**Comment by kishanprmr** [comment]
@coderbob2 I'm working on it.

**Comment by kishanprmr** [comment]
@allcontributors please add @coderbob2  for plugin

**Review by kishanprmr — APPROVED** [review]

**Pull request merged**
