### PR TITLE
feat(google-docs): add parent folder to  create-document action

### PR DESCRIPTION
**Pull request by olivierguzzi**
## What does this PR do?

Fixes # (issue)

### CODE REVIEW

**Comment by abuaboud** [comment]
Thank you 😁 will review it in the morning.

@allcontributors please add @olivierguzzi for plugin

**Review by abuaboud — CHANGES_REQUESTED** [review]
@olivierguzzi Thank you for opening the pr.

Parents parameter doesn't exist in google docs API, you need to use Google Drive API (file.update) to move file into folder check their documentation there:
https://developers.google.com/docs/api/how-tos/documents


I added the drive scopes there as the dropdown wasn't loading the folder.

**Comment by olivierguzzi** [comment]
@abuaboud Thanks ! I'll check and edit this soon.

I had trouble getting my local backend setup, there's something with the db schema. Maybe I'll need some help to be up and running on this, I need to dev a few components for my use case

**Comment by olivierguzzi** [comment]
@abuaboud Fixed using the google drive apis, i was able to test locally with the lasts pull ! thanks !

**Comment by abuaboud** [comment]
@olivierguzzi, I tried to test the step locally, I ended up with this error.


I checked the Google Drive API documentation at https://developers.google.com/drive/api/reference/rest/v3/files/create, and it seems that there is no `parents` field mentioned.

Based on the error message you provided, it appears that the API is returning a 400 error with the following details:
```
[API] [10:27:58 UTC] ERROR:   error: {
[API] [10:27:58 UTC] ERROR:     code: 400,
[API] [10:27:58 UTC] ERROR:     message: 'Invalid JSON payload received. Unknown name "parents": Cannot find field.',
[API] [10:27:58 UTC] ERROR:     status: 'INVALID_ARGUMENT',
[API] [10:27:58 UTC] ERROR:     details: [ [Object] ]
[API] [10:27:58 UTC] ERROR:   }
[API] [10:27:58 UTC] ERROR: }
```

Does it work for you?

**Pull request closed without merging**
