### PR TITLE
feat(discord): add ban guild member action

### PR DESCRIPTION
**Pull request by tintinthedev**
## What does this PR do?

Added the action to ban a member from a Discord guild.

### CODE REVIEW

**Comment by abuaboud** [comment]
Hi @tintinthedev 

Thank you for the contribution :D

Can you please bump the patch version in package.json and add yourself to authors in index.ts

**Review by pfernandez98 — CHANGES_REQUESTED** [review]
I think this file shouldn't be in the PR
`packages/ui/common/src/lib/environments/environment.ts`

Edit: Well I see now that the change was reversed lol

**Comment by tintinthedev** [comment]
> Hi @tintinthedev
> 
> Thank you for the contribution :D
> 
> Can you please bump the patch version in package.json and add yourself to authors in index.ts

Hey, just did it. I took so long because yesterday I went to college.

**Comment by pfernandez98** [comment]
Hey @tintinthedev, you need to do a couple of things: 

1. change the action variable name, right now is `discordAddRoleToMember`, it should be something like `discordBanGuildMember`
```typescript
export const discordAddRoleToMember = createAction({
``` 

2. Import the action in the `index.ts` file and add it to the `actions` array
```typescript
actions: [
    discordSendMessageWebhook,
    discordSendApprovalMessage,
    discordAddRoleToMember,
    discordRemoveRoleFromMember,
    discordRemoveMemberFromGuild,
    discordFindGuildMemberByUsername,
    discordRenameChannel,
    discordCreateChannel,
    discordDeleteChannel,
    discordFindChannel,
    //here the new action
    createCustomApiCallAction({
      baseUrl: () => {
        return 'https://discord.com/api/v9';
      },
      authMapping: (auth) => {
        return {
          Authorization: `Bearer ${auth}`,
        };
      },
    }),
  ],
```

**Comment by tintinthedev** [comment]
> Hey @tintinthedev, you need to do a couple of things:
> 
> 1. change the action variable name, right now is `discordAddRoleToMember`, it should be something like `discordBanGuildMember`
> 
> ```ts
> export const discordAddRoleToMember = createAction({
> ```
> 
> 2. Import the action in the `index.ts` file and add it to the `actions` array
> 
> ```ts
> actions: [
>     discordSendMessageWebhook,
>     discordSendApprovalMessage,
>     discordAddRoleToMember,
>     discordRemoveRoleFromMember,
>     discordRemoveMemberFromGuild,
>     discordFindGuildMemberByUsername,
>     discordRenameChannel,
>     discordCreateChannel,
>     discordDeleteChannel,
>     discordFindChannel,
>     //here the new action
>     createCustomApiCallAction({
>       baseUrl: () => {
>         return 'https://discord.com/api/v9';
>       },
>       authMapping: (auth) => {
>         return {
>           Authorization: `Bearer ${auth}`,
>         };
>       },
>     }),
>   ],
> ```

I'm working on changes right now. Should edit the PR soon. Thanks

**Comment by tintinthedev** [comment]
Hey @pfernandez98
Could you again check if everything is ok?

**Comment by pfernandez98** [comment]
> Hey @pfernandez98 Could you again check if everything is ok?

I think is Ok now, let's wait for someone to approve it

**Comment by abuaboud** [comment]
Thank you @pfernandez98  and @tintinthedev 

I will take look soon!

**Review by kishanprmr — APPROVED** [review]

**Pull request merged**
