### PR TITLE
feat(instasent): add or update contact, delete contact and create event action

### PR DESCRIPTION
**Pull request by dev-instasent**
Added Instasent piece that enables:
  - Contact management (add/update/delete)
  - Event tracking with dynamic parameters
  - Integration with Instasent's Ingest API

### CODE REVIEW

**Comment by kishanprmr** [comment]
@dev-instasent , can you sign the CLA certificate and provide API documentation for the /stream endpoint (used in auth validation) and /stream/specs/attributes? Also, could you guide me on how to get the project ID and data source ID? I tried using the one shown in the URL, but it didn't work.

**Comment by dev-instasent** [comment]
Hello @kishanprmr, thanks for taking your time into reviewing this.

I'm having issues to sign the license, the page does not fully load, I've tried to sign it a few times and I even received an email but it's not being detected as signed.

We have many customers requesting this integration, we have a dedicated data source for activepieces with specific instructions but it won't be pushed into production until this is merged. In the meantime, you can use the "Instasent API" data source, they're basically the same, in the setup instructions you have the 3 values that you need: Project ID / UID, Data source ID and Api key / Token

The specs endpoints were not publicly documented by design since we only use them for automation platforms and were developed ad-hoc. They have been added to the api docs and the README.md file has been updated.

**Comment by kishanprmr** [comment]
@allcontributors please add @dev-instasent  for plugin

**Comment by dev-instasent** [comment]
Hi @kishanprmr 

Thanks for merging our PR, we're ready to inform our customers about the availability but we have an issue and I'm not sure where should I report it:

In on-premise distributions it works perfectly but on your cloud service it does not work when trying to make a new connection. This is the response that is being received from your `app-connections` endpoint.

{
    "statusCode": 500,
    "code": "1",
    "error": "Internal Server Error",
    "message": "Command failed: pnpm add @activepieces/piece-instasent-0.0.1@npm:@activepieces/piece-instasent@0.0.1 --prefer-offline --ignore-scripts --config.lockfile=false --config.auto-install-peers=true\n"
}

This is the payload that was sent to it

{
    "externalId": "kjwo4vc1Chyh336MYafaR",
    "displayName": "Instasent",
    "pieceName": "@activepieces/piece-instasent",
    "projectId": "rCFQJOSY2nSeOviOtyQSv",
    "type": "CUSTOM_AUTH",
    "value": {
        "type": "CUSTOM_AUTH",
        "props": {
            "projectId": "my-company-d1",
            "datasourceId": "673dfac96b248b02e0226832",
            "apiKey": "XXXXXXXXXXXXXXXXXXXXXX"
        }
    }
}

Thanks!

**Pull request merged**
