### PR TITLE
chore: move ee-shared to shared

### PR DESCRIPTION
**Pull request by maor-rozenfeld**
To keep activepieces opensource, I've merged the ee-shared package with the shared package, since this package mainly contains entities (and not enterprise business logic), and it's being referenced everywhere.

Context:

- https://github.com/activepieces/activepieces/issues/3473
- https://community.activepieces.com/t/is-activepieces-still-open-source/2838‌

### CODE REVIEW

**Comment by abuaboud** [comment]
I think it might contribute to confusion which is open source and which is not, in open source edition it will serve a dead unused code.

**Comment by maor-rozenfeld** [comment]
> I think it might contribute to confusion which is open source and which is not, in open source edition it will serve a dead unused code.

Yea I agree that some of the entities aren't used, but some are already integrated with the open source code (OtpType, Platform, Project, etc.) and I think that at this point it's too much to separate them.

**Comment by abuaboud** [comment]
Let me check about other but for platform I think it should move with the logic too to open source 

https://github.com/activepieces/activepieces/pull/3722

**Comment by abuaboud** [comment]
It's much better to solve the root cause other than moving ee, I will have to scope

**Comment by maor-rozenfeld** [comment]
> It's much better to solve the root cause other than moving ee, I will have to scope

I can help with whatever approach you have in mind :)

**Comment by abuaboud** [comment]
These are the unique files that importing ee in the backend

```
1. `src/main.ts`
2. `src/app/core/security/authn/platform-api-key-authn-handler.ts`
3. `src/app/helper/logger.ts`
4. `src/app/app.ts`
5. `src/app/webhooks/webhook-controller.ts`
6. `src/app/user/user-service.ts`
7. `src/app/database/database-connection.ts`
8. `src/app/database/postgres-connection.ts`
```

I believe we should start with making backend only imports ee in single file (for example app.ts), this where it decides what to inject based on edition

**Comment by abuaboud** [comment]
1. `src/app/helper/logger.ts`
2. `src/app/user/user-service.ts`


I removed the reference there in another pr, so we have 6 places to go in the backend

**Comment by abuaboud** [comment]
@maor-rozenfeld I am closing this PR, please let's reopen when you are back

**Comment by maor-rozenfeld** [comment]
No worries @abuaboud , I will let you know if I start working on that. Thank you.

**Pull request closed without merging**
