### PR TITLE
feat: add version number to main page

### LINKED ISSUE #1704: Display version # on the main screen of GUI
Would it be possible to display the version number of the software on the main screen of the window?

I am using the self hosted docker image and as a relative newbie to self hosting, I wasn't able to check whether the container updated from 0.4.0 to 0.5.0.

Just a thought. Thanks :)

image

### PR DESCRIPTION
**Pull request by pfernandez98**
## What does this PR do?

This adds the current version number to the dashboard

Fixes #1704

### CODE REVIEW

**Comment by abuaboud** [comment]
Hi @pfernandez98 

Shit sorry, we recently added this (I think literally yesterday and i lost this ticket)

image

It's currently hidden in Admin Console -> Settings -> Updates

But in next task we will show some sort of notification when there is update 

I am closing this PR and the ticket, please let me know if you have any suggestions

**Comment by pfernandez98** [comment]
Hi! @abuaboud... I, as a selfhosted user, can't access to the Admin console (at least not for free)... What I did was add the current version number to the homepage, right beside the "User's Project", inside a chip

**Comment by abuaboud** [comment]
Hi @pfernandez98 

Admin console as concept is not premium, we will add many more features there for free around maintenance 

In this update you will see settings unlocked and this tab will be open, It's not obvious at the moment in next update, It will contain debugging information / trouble shooting / future breaking changes 

I hope this clear things up

**Comment by abuaboud** [comment]
Hi @pfernandez98 

I am also currently working on opening the users tab for free, where you can invite other users into same project, but everyone will have admin access, so we just want to make permissions as paid but multiple users in same platform for free.

**Comment by pfernandez98** [comment]
Oh thanks! I did not know that.

**Pull request closed without merging**
