### PR TITLE
feat(beamer): add changelog and notification center tool

### PR DESCRIPTION
**Pull request by i-nithin**
## Beamer - Changelog and notification center tool

Beamer piece 

Feature

### CODE REVIEW

**Comment by abuaboud** [comment]
@allcpntributors please add @i-nithin for plugin

**Comment by abuaboud** [comment]
@allcontributors please add @i-nithin for plugin

**Comment by abuaboud** [comment]
Hi @i-nithin Thank you and great job, The PR is now approved.

Do you mind sign the CLA So i can merge it in the codebase

**Review by abuaboud — APPROVED** [review]

**Review by i-nithin — COMMENTED** [review]
fix(beamer)

**Pull request merged**
