### PR TITLE
feat(ui): Internationalization - French

### PR DESCRIPTION
**Pull request by Doskyft**
## What does this PR do?

I started translating activepieces into French with @angular/localize.

Fixes # (issue)
https://github.com/activepieces/activepieces/issues/1467

### CODE REVIEW

**Comment by abuaboud** [comment]
This is elegant :D will take look soon

**Comment by abuaboud** [comment]
@AbdulTheActivePiecer can you please take look here as you better than me in Angular

**Comment by abuaboud** [comment]
Hi @Doskyft I am just want to say, we will merge this change soon we are trying to streamline some our documentation to align with this feature.

**Comment by Doskyft** [comment]
Hi @abuaboud !

That's great !

I'm not an expert in Angular at all, in fact this is the first project I've worked on with it, so if you have any suggestions on what I've done I'd greatly appreciate it.

Same for the nginx config, I'm not entirely convinced of what I did.

And this is also my first contribution to an open source project.

So I'm open to any advice.

**Comment by AbdulTheActivePiecer** [comment]
Hey buddy you can open this pr now, @abuaboud will give your nginx code a final review, just sync up with the main repo before you do so, if you get a conflict it is probably because some html without i18n directive was edited, thanks a lot for adding that directive to all the html files.

**Comment by abuaboud** [comment]
Hey @Doskyft! 

Right now, I'm working on making sure Nginx works for English by default without using '/en'. But I've got another issue where, after doing a Docker build, visiting 'localhost:8080' keeps redirecting to 'localhost/en' without '8080'.

We should also add how to contribute languages in the docs

I've got to say, this pull request really made my day! It's the best contribution I've ever seen for Activepieces. I'll sort out these issues and get them merged. 👍

**Comment by abuaboud** [comment]
Issues are solved, but I don't have permission to push to this branch.

Going to merge and open separate pr.

Do you mind @Doskyft If you open a docs pr how to contribute next texts and languages
 
Thank you.

**Comment by abuaboud** [comment]
The PR is now merged, Now let's add contribution docs along with badges to readme for language coverage

I am so excited for this change!

**Comment by Doskyft** [comment]
Hey @abuaboud 

I am very happy to help the project and delighted that my contribution is popular and that it is merged ❤

I'm trying to do the documentation next week

**Comment by stephaneleforestier** [comment]
@Doskyft congrats

**Pull request merged**
